# Predicción

- Objetivo: Generar las predicciones finales sobre el conjunto de datos sin etiqueta utilizando el modelo seleccionado durante la etapa de validación.

# Importación de Librerias

In [1]:
import pandas as pd

from pathlib import Path
import joblib

# PATHS

In [2]:
PROJECT_ROOT = Path.cwd().parent


PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
MODELS_DIR = PROJECT_ROOT / "models"
PREDICTIONS_DIR = PROJECT_ROOT / "predictions"
RAW_DIR = PROJECT_ROOT / "data" / "raw"

# Verificación PATHS

In [3]:
print(PROCESSED_DIR.exists())
print(MODELS_DIR.exists())
print(RAW_DIR.exists())

True
True
True

# Crear carpeta PREDICTIONS

In [4]:
PREDICTIONS_DIR.mkdir(exist_ok=True)

print("Carpeta predictions lista.")

Carpeta predictions lista.

# Cargar datos

In [5]:
test_fe = pd.read_csv(
    PROCESSED_DIR / "test_fe.csv"
)

print(test_fe.shape)

(5692, 24)

# Cargar Modelo

In [6]:
rf = joblib.load(
    MODELS_DIR / "random_forest_final.pkl"
)

print("Modelo cargado.")

Modelo cargado.

# Generar predicciones

In [7]:
predicciones = rf.predict(test_fe)

predicciones[:10]

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

# Recuperar Identificadores

- Se carga el DataSet original de entrega para recuperar la columna `ID`, la cual será utilizada para generar el archivo final de predicciones solicitado por la consigna.

In [8]:
entrega_original = pd.read_csv(
    RAW_DIR / "smoking_prediction_entrega.xlsx - smoking_prediction.csv"
)

print(entrega_original.shape)

(5692, 26)

# Verificación de Columnas

- Se verifica la existencia de la columna `ID` necesaria para la generación del archivo final de entrega.

In [9]:
print(entrega_original.columns.tolist())

['ID', 'gender', 'age', 'height(cm)', 'weight(kg)', 'waist(cm)', 'eyesight(left)', 'eyesight(right)', 'hearing(left)', 'hearing(right)', 'systolic', 'relaxation', 'fasting blood sugar', 'Cholesterol', 'triglyceride', 'HDL', 'LDL', 'hemoglobin', 'Urine protein', 'serum creatinine', 'AST', 'ALT', 'Gtp', 'oral', 'dental caries', 'tartar']

In [10]:
entrega_original[["ID"]].head()

      ID
0  27358
1  27364
2  27368
3  27378
4  27381

# Generación del Archivo Final

- Se combinan los identificadores originales con las predicciones generadas por el modelo Random Forest seleccionado durante la etapa de validación.

In [11]:
resultado_final = pd.DataFrame({
    "ID": entrega_original["ID"],
    "smoking_prediction": predicciones
})

resultado_final.head()

      ID  smoking_prediction
0  27358                   1
1  27364                   1
2  27368                   1
3  27378                   0
4  27381                   0

# Validación de dimensiones

- Se verifica que la cantidad de registros coincida entre el dataset original de entrega, el conjunto procesado y las predicciones generadas.

In [12]:
print("Dataset original :", len(entrega_original))
print("Dataset procesado:", len(test_fe))
print("Predicciones     :", len(predicciones))
print("Submission       :", len(resultado_final))

Dataset original : 5692
Dataset procesado: 5692
Predicciones     : 5692
Submission       : 5692

# Exportación de Predicciones

- Se exporta el archivo final con la estructura requerida para la entrega del TP2.

In [13]:
resultado_final.to_csv(
    PREDICTIONS_DIR / "smoking_prediction.csv",
    index=False
)

print("Archivo exportado correctamente.")

Archivo exportado correctamente.

In [14]:
resultado_final.head()

      ID  smoking_prediction
0  27358                   1
1  27364                   1
2  27368                   1
3  27378                   0
4  27381                   0

In [15]:
resultado_final.shape

(5692, 2)

In [16]:
resultado_final.columns

Index(['ID', 'smoking_prediction'], dtype='object')

# Conclusión

Se aplicó el pipeline de preprocesamiento desarrollado durante el proyecto y se utilizaron los modelos entrenados para generar las predicciones finales sobre el conjunto de datos sin etiqueta.

El modelo seleccionado fue Random Forest, debido a su mejor desempeño en la métrica F1-Score para la clase objetivo.

Como resultado se generó un archivo de salida con:

- ID
- smoking_prediction

listo para su utilización en la entrega del TP2.-